'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmHistorial
    
    '''<summary>
    '''hdfSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSelector As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''cmbTipoHistorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoHistorial As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divTodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTodo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divModulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cmbModuloTipoModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbModuloTipoModulo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbporModuloporFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbporModuloporFecha As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divmoduloxFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divmoduloxFecha As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbporModuloFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbporModuloFecha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divmoduloxFechas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divmoduloxFechas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbporModuloFechaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbporModuloFechaInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txbModuloFechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbModuloFechaFinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUsuario As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cmbporUsuarioPorUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbporUsuarioPorUsuario As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbporUsuarioModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbporUsuarioModulo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbusuarioModuloxFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbusuarioModuloxFecha As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divUsuarioModuloxFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUsuarioModuloxFecha As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbusuariomoduloxfecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbusuariomoduloxfecha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divUsuarioModuloxFechas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUsuarioModuloxFechas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbusuariomodulofInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbusuariomodulofInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txbusuariomodulofFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbusuariomodulofFinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFecha As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbPorFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPorFecha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divRangoFechas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRangoFechas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbPorRangoFechaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPorRangoFechaInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txbPorRangoFechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPorRangoFechaFinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divEdicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEdicion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cmbPorTipoEdicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPorTipoEdicion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbEdicionModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEdicionModulo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbEdicionModuloxFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEdicionModuloxFecha As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divEdicionModuloxFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEdicionModuloxFecha As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbedicionmodulofecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbedicionmodulofecha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divEdicionModuloxFechas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEdicionModuloxFechas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txbedicionmodulofechaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbedicionmodulofechaInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txbedicionmodulofechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbedicionmodulofechaFinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblhistorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhistorial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updateListado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateListado As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lsvHistoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsvHistoria As Global.System.Web.UI.WebControls.ListView
End Class
